"""Writes the icons as HVIF resources ('VICN') into an Icons.rdef per
target: python3 tools/icons/build.py (from the repository root).

The .rdef files are generated - change icons.py and run this again.
The HVIF data can also be opened and edited in Icon-O-Matic.
"""

import os

import hvif
from icons import ICONS

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'src')
TARGETS = {
    'app': 'app/Icons.rdef',
    'GraphEditor': 'plugins/GraphEditor/Icons.rdef',
    'LayoutEditor': 'plugins/LayoutEditor/Icons.rdef',
}
FIRST_ID = 1000


def rdef_array(data):
    lines = []
    for i in range(0, len(data), 32):
        lines.append('\t$"%s"' % data[i:i + 32].hex().upper())
    return '\n'.join(lines)


def main():
    for target, path in TARGETS.items():
        out = ['/* generated by tools/icons/build.py from tools/icons/icons.py */', '']
        number = FIRST_ID
        for name, (where, builder) in ICONS.items():
            if where != target:
                continue
            data = hvif.encode(builder())
            out.append('resource(%d, "%s") #\'VICN\' array {' % (number, name))
            out.append(rdef_array(data))
            out.append('};')
            out.append('')
            number += 1
        with open(os.path.join(ROOT, path), 'w') as rdef:
            rdef.write('\n'.join(out))
        print(path, number - FIRST_ID, 'icons')


if __name__ == '__main__':
    main()
