first: default

addattributecommand: AddAttributeCommand/makefile FORCE
	cd AddAttributeCommand && make

addattributecommand_clean:
	cd AddAttributeCommand && make clean

changevaluecommand: ChangeValueCommand/makefile FORCE
	cd ChangeValueCommand && make

changevaluecommand_clean:
	cd ChangeValueCommand && make clean

copycommand: CopyCommand/makefile FORCE
	cd CopyCommand && make

copycommand_clean:
	cd CopyCommand && make clean

deletecommand: DeleteCommand/makefile FORCE
	cd DeleteCommand && make

deletecommand_clean:
	cd DeleteCommand && make clean

findcommand: FindCommand/makefile FORCE
	cd FindCommand && make

findcommand_clean:
	cd FindCommand && make clean

freemindtranslator: FreeMindTranslator/makefile FORCE
	cd FreeMindTranslator && make

freemindtranslator_clean:
	cd FreeMindTranslator && make clean

grapheditor: GraphEditor/makefile FORCE
	cd GraphEditor && make

grapheditor_clean:
	cd GraphEditor && make clean

groupcommand: GroupCommand/makefile FORCE
	cd GroupCommand && make

groupcommand_clean:
	cd GroupCommand && make clean

insertcommand: InsertCommand/makefile FORCE
	cd InsertCommand && make

insertcommand_clean:
	cd InsertCommand && make clean

movecommand: MoveCommand/makefile FORCE
	cd MoveCommand && make

movecommand_clean:
	cd MoveCommand && make clean

navigatoreditor: NavigatorEditor/makefile FORCE
	cd NavigatorEditor && make

navigatoreditor_clean:
	cd NavigatorEditor && make clean

pastecommand: PasteCommand/makefile FORCE
	cd PasteCommand && make

pastecommand_clean:
	cd PasteCommand && make clean

removeattributecommand: RemoveAttributeCommand/makefile FORCE
	cd RemoveAttributeCommand && make

removeattributecommand_clean:
	cd RemoveAttributeCommand && make clean

resizecommand: ResizeCommand/makefile FORCE
	cd ResizeCommand && make

resizecommand_clean:
	cd ResizeCommand && make clean

selectcommand: SelectCommand/makefile FORCE
	cd SelectCommand && make

selectcommand_clean:
	cd SelectCommand && make clean

standardtranslator: StandardTranslator/makefile FORCE
	cd StandardTranslator && make

standardtranslator_clean:
	cd StandardTranslator && make clean

default: \
	addattributecommand \
	changevaluecommand \
	copycommand \
	deletecommand \
	findcommand \
	freemindtranslator \
	grapheditor \
	groupcommand \
	insertcommand \
	movecommand \
	navigatoreditor \
	pastecommand \
	removeattributecommand \
	resizecommand \
	selectcommand \
	standardtranslator

clean: \
	addattributecommand_clean \
	changevaluecommand_clean \
	copycommand_clean \
	deletecommand_clean \
	findcommand_clean \
	freemindtranslator_clean \
	grapheditor_clean \
	groupcommand_clean \
	insertcommand_clean \
	movecommand_clean \
	navigatoreditor_clean \
	pastecommand_clean \
	removeattributecommand_clean \
	resizecommand_clean \
	selectcommand_clean \
	standardtranslator_clean

FORCE:
